### ISSUE TITLE
Possible incompatibilities with mods using .toml for config

### ISSUE THREAD

**Issue by lord-oats** [Quplet/NoShieldDelay#5]
Mod causes Minecraft to crash on startup when using the following mods:
Comforts https://modrinth.com/mod/comforts
Vein Mining https://modrinth.com/mod/vein-mining

As far as I can tell, it's because they both also use .toml config files which could be causing issues, although I may be wrong.

[crash-2024-07-14_22.16.04-client.txt](https://github.com/user-attachments/files/16228835/crash-2024-07-14_22.16.04-client.txt)
[crash-2024-07-14_22.17.00-client.txt](https://github.com/user-attachments/files/16228836/crash-2024-07-14_22.17.00-client.txt)

**Comment by Quplet** [comment]
The issue is superseding night config libraries. A recent version of night configs has a massive regression that breaks my config system and causes a crash and if any mod includes that version with the regression it breaks.

See issue #2 for a replacement version of the mod that excludes this regression.
